spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    refreshTokenExpiration: 604800 #7d
    accessTokenExpiration: 300 #5m

  profiles:
    active: dev

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
